// Wygenerowane z PokéAPI — pełny Pokédex z typami (PL).
export type DexEntry = { id: number; name: string; type: string; types: string[] };

export const FULL_DEX: DexEntry[] = [
  { id: 1, name: "Bulbasaur", type: "Trawa", types: ["Trawa", "Trucizna"] },
  { id: 2, name: "Ivysaur", type: "Trawa", types: ["Trawa", "Trucizna"] },
  { id: 3, name: "Venusaur", type: "Trawa", types: ["Trawa", "Trucizna"] },
  { id: 4, name: "Charmander", type: "Ogień", types: ["Ogień"] },
  { id: 5, name: "Charmeleon", type: "Ogień", types: ["Ogień"] },
  { id: 6, name: "Charizard", type: "Ogień", types: ["Ogień", "Lot"] },
  { id: 7, name: "Squirtle", type: "Woda", types: ["Woda"] },
  { id: 8, name: "Wartortle", type: "Woda", types: ["Woda"] },
  { id: 9, name: "Blastoise", type: "Woda", types: ["Woda"] },
  { id: 10, name: "Caterpie", type: "Robak", types: ["Robak"] },
  { id: 11, name: "Metapod", type: "Robak", types: ["Robak"] },
  { id: 12, name: "Butterfree", type: "Robak", types: ["Robak", "Lot"] },
  { id: 13, name: "Weedle", type: "Robak", types: ["Robak", "Trucizna"] },
  { id: 14, name: "Kakuna", type: "Robak", types: ["Robak", "Trucizna"] },
  { id: 15, name: "Beedrill", type: "Robak", types: ["Robak", "Trucizna"] },
  { id: 16, name: "Pidgey", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 17, name: "Pidgeotto", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 18, name: "Pidgeot", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 19, name: "Rattata", type: "Normalny", types: ["Normalny"] },
  { id: 20, name: "Raticate", type: "Normalny", types: ["Normalny"] },
  { id: 21, name: "Spearow", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 22, name: "Fearow", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 23, name: "Ekans", type: "Trucizna", types: ["Trucizna"] },
  { id: 24, name: "Arbok", type: "Trucizna", types: ["Trucizna"] },
  { id: 25, name: "Pikachu", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 26, name: "Raichu", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 27, name: "Sandshrew", type: "Ziemia", types: ["Ziemia"] },
  { id: 28, name: "Sandslash", type: "Ziemia", types: ["Ziemia"] },
  { id: 29, name: "Nidoran-f", type: "Trucizna", types: ["Trucizna"] },
  { id: 30, name: "Nidorina", type: "Trucizna", types: ["Trucizna"] },
  { id: 31, name: "Nidoqueen", type: "Trucizna", types: ["Trucizna", "Ziemia"] },
  { id: 32, name: "Nidoran-m", type: "Trucizna", types: ["Trucizna"] },
  { id: 33, name: "Nidorino", type: "Trucizna", types: ["Trucizna"] },
  { id: 34, name: "Nidoking", type: "Trucizna", types: ["Trucizna", "Ziemia"] },
  { id: 35, name: "Clefairy", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 36, name: "Clefable", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 37, name: "Vulpix", type: "Ogień", types: ["Ogień"] },
  { id: 38, name: "Ninetales", type: "Ogień", types: ["Ogień"] },
  { id: 39, name: "Jigglypuff", type: "Normalny", types: ["Normalny", "Baśniowy"] },
  { id: 40, name: "Wigglytuff", type: "Normalny", types: ["Normalny", "Baśniowy"] },
  { id: 41, name: "Zubat", type: "Trucizna", types: ["Trucizna", "Lot"] },
  { id: 42, name: "Golbat", type: "Trucizna", types: ["Trucizna", "Lot"] },
  { id: 43, name: "Oddish", type: "Trawa", types: ["Trawa", "Trucizna"] },
  { id: 44, name: "Gloom", type: "Trawa", types: ["Trawa", "Trucizna"] },
  { id: 45, name: "Vileplume", type: "Trawa", types: ["Trawa", "Trucizna"] },
  { id: 46, name: "Paras", type: "Robak", types: ["Robak", "Trawa"] },
  { id: 47, name: "Parasect", type: "Robak", types: ["Robak", "Trawa"] },
  { id: 48, name: "Venonat", type: "Robak", types: ["Robak", "Trucizna"] },
  { id: 49, name: "Venomoth", type: "Robak", types: ["Robak", "Trucizna"] },
  { id: 50, name: "Diglett", type: "Ziemia", types: ["Ziemia"] },
  { id: 51, name: "Dugtrio", type: "Ziemia", types: ["Ziemia"] },
  { id: 52, name: "Meowth", type: "Normalny", types: ["Normalny"] },
  { id: 53, name: "Persian", type: "Normalny", types: ["Normalny"] },
  { id: 54, name: "Psyduck", type: "Woda", types: ["Woda"] },
  { id: 55, name: "Golduck", type: "Woda", types: ["Woda"] },
  { id: 56, name: "Mankey", type: "Walka", types: ["Walka"] },
  { id: 57, name: "Primeape", type: "Walka", types: ["Walka"] },
  { id: 58, name: "Growlithe", type: "Ogień", types: ["Ogień"] },
  { id: 59, name: "Arcanine", type: "Ogień", types: ["Ogień"] },
  { id: 60, name: "Poliwag", type: "Woda", types: ["Woda"] },
  { id: 61, name: "Poliwhirl", type: "Woda", types: ["Woda"] },
  { id: 62, name: "Poliwrath", type: "Woda", types: ["Woda", "Walka"] },
  { id: 63, name: "Abra", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 64, name: "Kadabra", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 65, name: "Alakazam", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 66, name: "Machop", type: "Walka", types: ["Walka"] },
  { id: 67, name: "Machoke", type: "Walka", types: ["Walka"] },
  { id: 68, name: "Machamp", type: "Walka", types: ["Walka"] },
  { id: 69, name: "Bellsprout", type: "Trawa", types: ["Trawa", "Trucizna"] },
  { id: 70, name: "Weepinbell", type: "Trawa", types: ["Trawa", "Trucizna"] },
  { id: 71, name: "Victreebel", type: "Trawa", types: ["Trawa", "Trucizna"] },
  { id: 72, name: "Tentacool", type: "Woda", types: ["Woda", "Trucizna"] },
  { id: 73, name: "Tentacruel", type: "Woda", types: ["Woda", "Trucizna"] },
  { id: 74, name: "Geodude", type: "Skała", types: ["Skała", "Ziemia"] },
  { id: 75, name: "Graveler", type: "Skała", types: ["Skała", "Ziemia"] },
  { id: 76, name: "Golem", type: "Skała", types: ["Skała", "Ziemia"] },
  { id: 77, name: "Ponyta", type: "Ogień", types: ["Ogień"] },
  { id: 78, name: "Rapidash", type: "Ogień", types: ["Ogień"] },
  { id: 79, name: "Slowpoke", type: "Woda", types: ["Woda", "Psychiczny"] },
  { id: 80, name: "Slowbro", type: "Woda", types: ["Woda", "Psychiczny"] },
  { id: 81, name: "Magnemite", type: "Elektryczny", types: ["Elektryczny", "Stal"] },
  { id: 82, name: "Magneton", type: "Elektryczny", types: ["Elektryczny", "Stal"] },
  { id: 83, name: "Farfetchd", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 84, name: "Doduo", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 85, name: "Dodrio", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 86, name: "Seel", type: "Woda", types: ["Woda"] },
  { id: 87, name: "Dewgong", type: "Woda", types: ["Woda", "Lód"] },
  { id: 88, name: "Grimer", type: "Trucizna", types: ["Trucizna"] },
  { id: 89, name: "Muk", type: "Trucizna", types: ["Trucizna"] },
  { id: 90, name: "Shellder", type: "Woda", types: ["Woda"] },
  { id: 91, name: "Cloyster", type: "Woda", types: ["Woda", "Lód"] },
  { id: 92, name: "Gastly", type: "Duch", types: ["Duch", "Trucizna"] },
  { id: 93, name: "Haunter", type: "Duch", types: ["Duch", "Trucizna"] },
  { id: 94, name: "Gengar", type: "Duch", types: ["Duch", "Trucizna"] },
  { id: 95, name: "Onix", type: "Skała", types: ["Skała", "Ziemia"] },
  { id: 96, name: "Drowzee", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 97, name: "Hypno", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 98, name: "Krabby", type: "Woda", types: ["Woda"] },
  { id: 99, name: "Kingler", type: "Woda", types: ["Woda"] },
  { id: 100, name: "Voltorb", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 101, name: "Electrode", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 102, name: "Exeggcute", type: "Trawa", types: ["Trawa", "Psychiczny"] },
  { id: 103, name: "Exeggutor", type: "Trawa", types: ["Trawa", "Psychiczny"] },
  { id: 104, name: "Cubone", type: "Ziemia", types: ["Ziemia"] },
  { id: 105, name: "Marowak", type: "Ziemia", types: ["Ziemia"] },
  { id: 106, name: "Hitmonlee", type: "Walka", types: ["Walka"] },
  { id: 107, name: "Hitmonchan", type: "Walka", types: ["Walka"] },
  { id: 108, name: "Lickitung", type: "Normalny", types: ["Normalny"] },
  { id: 109, name: "Koffing", type: "Trucizna", types: ["Trucizna"] },
  { id: 110, name: "Weezing", type: "Trucizna", types: ["Trucizna"] },
  { id: 111, name: "Rhyhorn", type: "Ziemia", types: ["Ziemia", "Skała"] },
  { id: 112, name: "Rhydon", type: "Ziemia", types: ["Ziemia", "Skała"] },
  { id: 113, name: "Chansey", type: "Normalny", types: ["Normalny"] },
  { id: 114, name: "Tangela", type: "Trawa", types: ["Trawa"] },
  { id: 115, name: "Kangaskhan", type: "Normalny", types: ["Normalny"] },
  { id: 116, name: "Horsea", type: "Woda", types: ["Woda"] },
  { id: 117, name: "Seadra", type: "Woda", types: ["Woda"] },
  { id: 118, name: "Goldeen", type: "Woda", types: ["Woda"] },
  { id: 119, name: "Seaking", type: "Woda", types: ["Woda"] },
  { id: 120, name: "Staryu", type: "Woda", types: ["Woda"] },
  { id: 121, name: "Starmie", type: "Woda", types: ["Woda", "Psychiczny"] },
  { id: 122, name: "Mr-mime", type: "Psychiczny", types: ["Psychiczny", "Baśniowy"] },
  { id: 123, name: "Scyther", type: "Robak", types: ["Robak", "Lot"] },
  { id: 124, name: "Jynx", type: "Lód", types: ["Lód", "Psychiczny"] },
  { id: 125, name: "Electabuzz", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 126, name: "Magmar", type: "Ogień", types: ["Ogień"] },
  { id: 127, name: "Pinsir", type: "Robak", types: ["Robak"] },
  { id: 128, name: "Tauros", type: "Normalny", types: ["Normalny"] },
  { id: 129, name: "Magikarp", type: "Woda", types: ["Woda"] },
  { id: 130, name: "Gyarados", type: "Woda", types: ["Woda", "Lot"] },
  { id: 131, name: "Lapras", type: "Woda", types: ["Woda", "Lód"] },
  { id: 132, name: "Ditto", type: "Normalny", types: ["Normalny"] },
  { id: 133, name: "Eevee", type: "Normalny", types: ["Normalny"] },
  { id: 134, name: "Vaporeon", type: "Woda", types: ["Woda"] },
  { id: 135, name: "Jolteon", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 136, name: "Flareon", type: "Ogień", types: ["Ogień"] },
  { id: 137, name: "Porygon", type: "Normalny", types: ["Normalny"] },
  { id: 138, name: "Omanyte", type: "Skała", types: ["Skała", "Woda"] },
  { id: 139, name: "Omastar", type: "Skała", types: ["Skała", "Woda"] },
  { id: 140, name: "Kabuto", type: "Skała", types: ["Skała", "Woda"] },
  { id: 141, name: "Kabutops", type: "Skała", types: ["Skała", "Woda"] },
  { id: 142, name: "Aerodactyl", type: "Skała", types: ["Skała", "Lot"] },
  { id: 143, name: "Snorlax", type: "Normalny", types: ["Normalny"] },
  { id: 144, name: "Articuno", type: "Lód", types: ["Lód", "Lot"] },
  { id: 145, name: "Zapdos", type: "Elektryczny", types: ["Elektryczny", "Lot"] },
  { id: 146, name: "Moltres", type: "Ogień", types: ["Ogień", "Lot"] },
  { id: 147, name: "Dratini", type: "Smok", types: ["Smok"] },
  { id: 148, name: "Dragonair", type: "Smok", types: ["Smok"] },
  { id: 149, name: "Dragonite", type: "Smok", types: ["Smok", "Lot"] },
  { id: 150, name: "Mewtwo", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 151, name: "Mew", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 152, name: "Chikorita", type: "Trawa", types: ["Trawa"] },
  { id: 153, name: "Bayleef", type: "Trawa", types: ["Trawa"] },
  { id: 154, name: "Meganium", type: "Trawa", types: ["Trawa"] },
  { id: 155, name: "Cyndaquil", type: "Ogień", types: ["Ogień"] },
  { id: 156, name: "Quilava", type: "Ogień", types: ["Ogień"] },
  { id: 157, name: "Typhlosion", type: "Ogień", types: ["Ogień"] },
  { id: 158, name: "Totodile", type: "Woda", types: ["Woda"] },
  { id: 159, name: "Croconaw", type: "Woda", types: ["Woda"] },
  { id: 160, name: "Feraligatr", type: "Woda", types: ["Woda"] },
  { id: 161, name: "Sentret", type: "Normalny", types: ["Normalny"] },
  { id: 162, name: "Furret", type: "Normalny", types: ["Normalny"] },
  { id: 163, name: "Hoothoot", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 164, name: "Noctowl", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 165, name: "Ledyba", type: "Robak", types: ["Robak", "Lot"] },
  { id: 166, name: "Ledian", type: "Robak", types: ["Robak", "Lot"] },
  { id: 167, name: "Spinarak", type: "Robak", types: ["Robak", "Trucizna"] },
  { id: 168, name: "Ariados", type: "Robak", types: ["Robak", "Trucizna"] },
  { id: 169, name: "Crobat", type: "Trucizna", types: ["Trucizna", "Lot"] },
  { id: 170, name: "Chinchou", type: "Woda", types: ["Woda", "Elektryczny"] },
  { id: 171, name: "Lanturn", type: "Woda", types: ["Woda", "Elektryczny"] },
  { id: 172, name: "Pichu", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 173, name: "Cleffa", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 174, name: "Igglybuff", type: "Normalny", types: ["Normalny", "Baśniowy"] },
  { id: 175, name: "Togepi", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 176, name: "Togetic", type: "Baśniowy", types: ["Baśniowy", "Lot"] },
  { id: 177, name: "Natu", type: "Psychiczny", types: ["Psychiczny", "Lot"] },
  { id: 178, name: "Xatu", type: "Psychiczny", types: ["Psychiczny", "Lot"] },
  { id: 179, name: "Mareep", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 180, name: "Flaaffy", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 181, name: "Ampharos", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 182, name: "Bellossom", type: "Trawa", types: ["Trawa"] },
  { id: 183, name: "Marill", type: "Woda", types: ["Woda", "Baśniowy"] },
  { id: 184, name: "Azumarill", type: "Woda", types: ["Woda", "Baśniowy"] },
  { id: 185, name: "Sudowoodo", type: "Skała", types: ["Skała"] },
  { id: 186, name: "Politoed", type: "Woda", types: ["Woda"] },
  { id: 187, name: "Hoppip", type: "Trawa", types: ["Trawa", "Lot"] },
  { id: 188, name: "Skiploom", type: "Trawa", types: ["Trawa", "Lot"] },
  { id: 189, name: "Jumpluff", type: "Trawa", types: ["Trawa", "Lot"] },
  { id: 190, name: "Aipom", type: "Normalny", types: ["Normalny"] },
  { id: 191, name: "Sunkern", type: "Trawa", types: ["Trawa"] },
  { id: 192, name: "Sunflora", type: "Trawa", types: ["Trawa"] },
  { id: 193, name: "Yanma", type: "Robak", types: ["Robak", "Lot"] },
  { id: 194, name: "Wooper", type: "Woda", types: ["Woda", "Ziemia"] },
  { id: 195, name: "Quagsire", type: "Woda", types: ["Woda", "Ziemia"] },
  { id: 196, name: "Espeon", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 197, name: "Umbreon", type: "Ciemność", types: ["Ciemność"] },
  { id: 198, name: "Murkrow", type: "Ciemność", types: ["Ciemność", "Lot"] },
  { id: 199, name: "Slowking", type: "Woda", types: ["Woda", "Psychiczny"] },
  { id: 200, name: "Misdreavus", type: "Duch", types: ["Duch"] },
  { id: 201, name: "Unown", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 202, name: "Wobbuffet", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 203, name: "Girafarig", type: "Normalny", types: ["Normalny", "Psychiczny"] },
  { id: 204, name: "Pineco", type: "Robak", types: ["Robak"] },
  { id: 205, name: "Forretress", type: "Robak", types: ["Robak", "Stal"] },
  { id: 206, name: "Dunsparce", type: "Normalny", types: ["Normalny"] },
  { id: 207, name: "Gligar", type: "Ziemia", types: ["Ziemia", "Lot"] },
  { id: 208, name: "Steelix", type: "Stal", types: ["Stal", "Ziemia"] },
  { id: 209, name: "Snubbull", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 210, name: "Granbull", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 211, name: "Qwilfish", type: "Woda", types: ["Woda", "Trucizna"] },
  { id: 212, name: "Scizor", type: "Robak", types: ["Robak", "Stal"] },
  { id: 213, name: "Shuckle", type: "Robak", types: ["Robak", "Skała"] },
  { id: 214, name: "Heracross", type: "Robak", types: ["Robak", "Walka"] },
  { id: 215, name: "Sneasel", type: "Ciemność", types: ["Ciemność", "Lód"] },
  { id: 216, name: "Teddiursa", type: "Normalny", types: ["Normalny"] },
  { id: 217, name: "Ursaring", type: "Normalny", types: ["Normalny"] },
  { id: 218, name: "Slugma", type: "Ogień", types: ["Ogień"] },
  { id: 219, name: "Magcargo", type: "Ogień", types: ["Ogień", "Skała"] },
  { id: 220, name: "Swinub", type: "Lód", types: ["Lód", "Ziemia"] },
  { id: 221, name: "Piloswine", type: "Lód", types: ["Lód", "Ziemia"] },
  { id: 222, name: "Corsola", type: "Woda", types: ["Woda", "Skała"] },
  { id: 223, name: "Remoraid", type: "Woda", types: ["Woda"] },
  { id: 224, name: "Octillery", type: "Woda", types: ["Woda"] },
  { id: 225, name: "Delibird", type: "Lód", types: ["Lód", "Lot"] },
  { id: 226, name: "Mantine", type: "Woda", types: ["Woda", "Lot"] },
  { id: 227, name: "Skarmory", type: "Stal", types: ["Stal", "Lot"] },
  { id: 228, name: "Houndour", type: "Ciemność", types: ["Ciemność", "Ogień"] },
  { id: 229, name: "Houndoom", type: "Ciemność", types: ["Ciemność", "Ogień"] },
  { id: 230, name: "Kingdra", type: "Woda", types: ["Woda", "Smok"] },
  { id: 231, name: "Phanpy", type: "Ziemia", types: ["Ziemia"] },
  { id: 232, name: "Donphan", type: "Ziemia", types: ["Ziemia"] },
  { id: 233, name: "Porygon2", type: "Normalny", types: ["Normalny"] },
  { id: 234, name: "Stantler", type: "Normalny", types: ["Normalny"] },
  { id: 235, name: "Smeargle", type: "Normalny", types: ["Normalny"] },
  { id: 236, name: "Tyrogue", type: "Walka", types: ["Walka"] },
  { id: 237, name: "Hitmontop", type: "Walka", types: ["Walka"] },
  { id: 238, name: "Smoochum", type: "Lód", types: ["Lód", "Psychiczny"] },
  { id: 239, name: "Elekid", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 240, name: "Magby", type: "Ogień", types: ["Ogień"] },
  { id: 241, name: "Miltank", type: "Normalny", types: ["Normalny"] },
  { id: 242, name: "Blissey", type: "Normalny", types: ["Normalny"] },
  { id: 243, name: "Raikou", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 244, name: "Entei", type: "Ogień", types: ["Ogień"] },
  { id: 245, name: "Suicune", type: "Woda", types: ["Woda"] },
  { id: 246, name: "Larvitar", type: "Skała", types: ["Skała", "Ziemia"] },
  { id: 247, name: "Pupitar", type: "Skała", types: ["Skała", "Ziemia"] },
  { id: 248, name: "Tyranitar", type: "Skała", types: ["Skała", "Ciemność"] },
  { id: 249, name: "Lugia", type: "Psychiczny", types: ["Psychiczny", "Lot"] },
  { id: 250, name: "Ho-oh", type: "Ogień", types: ["Ogień", "Lot"] },
  { id: 251, name: "Celebi", type: "Psychiczny", types: ["Psychiczny", "Trawa"] },
  { id: 252, name: "Treecko", type: "Trawa", types: ["Trawa"] },
  { id: 253, name: "Grovyle", type: "Trawa", types: ["Trawa"] },
  { id: 254, name: "Sceptile", type: "Trawa", types: ["Trawa"] },
  { id: 255, name: "Torchic", type: "Ogień", types: ["Ogień"] },
  { id: 256, name: "Combusken", type: "Ogień", types: ["Ogień", "Walka"] },
  { id: 257, name: "Blaziken", type: "Ogień", types: ["Ogień", "Walka"] },
  { id: 258, name: "Mudkip", type: "Woda", types: ["Woda"] },
  { id: 259, name: "Marshtomp", type: "Woda", types: ["Woda", "Ziemia"] },
  { id: 260, name: "Swampert", type: "Woda", types: ["Woda", "Ziemia"] },
  { id: 261, name: "Poochyena", type: "Ciemność", types: ["Ciemność"] },
  { id: 262, name: "Mightyena", type: "Ciemność", types: ["Ciemność"] },
  { id: 263, name: "Zigzagoon", type: "Normalny", types: ["Normalny"] },
  { id: 264, name: "Linoone", type: "Normalny", types: ["Normalny"] },
  { id: 265, name: "Wurmple", type: "Robak", types: ["Robak"] },
  { id: 266, name: "Silcoon", type: "Robak", types: ["Robak"] },
  { id: 267, name: "Beautifly", type: "Robak", types: ["Robak", "Lot"] },
  { id: 268, name: "Cascoon", type: "Robak", types: ["Robak"] },
  { id: 269, name: "Dustox", type: "Robak", types: ["Robak", "Trucizna"] },
  { id: 270, name: "Lotad", type: "Woda", types: ["Woda", "Trawa"] },
  { id: 271, name: "Lombre", type: "Woda", types: ["Woda", "Trawa"] },
  { id: 272, name: "Ludicolo", type: "Woda", types: ["Woda", "Trawa"] },
  { id: 273, name: "Seedot", type: "Trawa", types: ["Trawa"] },
  { id: 274, name: "Nuzleaf", type: "Trawa", types: ["Trawa", "Ciemność"] },
  { id: 275, name: "Shiftry", type: "Trawa", types: ["Trawa", "Ciemność"] },
  { id: 276, name: "Taillow", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 277, name: "Swellow", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 278, name: "Wingull", type: "Woda", types: ["Woda", "Lot"] },
  { id: 279, name: "Pelipper", type: "Woda", types: ["Woda", "Lot"] },
  { id: 280, name: "Ralts", type: "Psychiczny", types: ["Psychiczny", "Baśniowy"] },
  { id: 281, name: "Kirlia", type: "Psychiczny", types: ["Psychiczny", "Baśniowy"] },
  { id: 282, name: "Gardevoir", type: "Psychiczny", types: ["Psychiczny", "Baśniowy"] },
  { id: 283, name: "Surskit", type: "Robak", types: ["Robak", "Woda"] },
  { id: 284, name: "Masquerain", type: "Robak", types: ["Robak", "Lot"] },
  { id: 285, name: "Shroomish", type: "Trawa", types: ["Trawa"] },
  { id: 286, name: "Breloom", type: "Trawa", types: ["Trawa", "Walka"] },
  { id: 287, name: "Slakoth", type: "Normalny", types: ["Normalny"] },
  { id: 288, name: "Vigoroth", type: "Normalny", types: ["Normalny"] },
  { id: 289, name: "Slaking", type: "Normalny", types: ["Normalny"] },
  { id: 290, name: "Nincada", type: "Robak", types: ["Robak", "Ziemia"] },
  { id: 291, name: "Ninjask", type: "Robak", types: ["Robak", "Lot"] },
  { id: 292, name: "Shedinja", type: "Robak", types: ["Robak", "Duch"] },
  { id: 293, name: "Whismur", type: "Normalny", types: ["Normalny"] },
  { id: 294, name: "Loudred", type: "Normalny", types: ["Normalny"] },
  { id: 295, name: "Exploud", type: "Normalny", types: ["Normalny"] },
  { id: 296, name: "Makuhita", type: "Walka", types: ["Walka"] },
  { id: 297, name: "Hariyama", type: "Walka", types: ["Walka"] },
  { id: 298, name: "Azurill", type: "Normalny", types: ["Normalny", "Baśniowy"] },
  { id: 299, name: "Nosepass", type: "Skała", types: ["Skała"] },
  { id: 300, name: "Skitty", type: "Normalny", types: ["Normalny"] },
  { id: 301, name: "Delcatty", type: "Normalny", types: ["Normalny"] },
  { id: 302, name: "Sableye", type: "Ciemność", types: ["Ciemność", "Duch"] },
  { id: 303, name: "Mawile", type: "Stal", types: ["Stal", "Baśniowy"] },
  { id: 304, name: "Aron", type: "Stal", types: ["Stal", "Skała"] },
  { id: 305, name: "Lairon", type: "Stal", types: ["Stal", "Skała"] },
  { id: 306, name: "Aggron", type: "Stal", types: ["Stal", "Skała"] },
  { id: 307, name: "Meditite", type: "Walka", types: ["Walka", "Psychiczny"] },
  { id: 308, name: "Medicham", type: "Walka", types: ["Walka", "Psychiczny"] },
  { id: 309, name: "Electrike", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 310, name: "Manectric", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 311, name: "Plusle", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 312, name: "Minun", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 313, name: "Volbeat", type: "Robak", types: ["Robak"] },
  { id: 314, name: "Illumise", type: "Robak", types: ["Robak"] },
  { id: 315, name: "Roselia", type: "Trawa", types: ["Trawa", "Trucizna"] },
  { id: 316, name: "Gulpin", type: "Trucizna", types: ["Trucizna"] },
  { id: 317, name: "Swalot", type: "Trucizna", types: ["Trucizna"] },
  { id: 318, name: "Carvanha", type: "Woda", types: ["Woda", "Ciemność"] },
  { id: 319, name: "Sharpedo", type: "Woda", types: ["Woda", "Ciemność"] },
  { id: 320, name: "Wailmer", type: "Woda", types: ["Woda"] },
  { id: 321, name: "Wailord", type: "Woda", types: ["Woda"] },
  { id: 322, name: "Numel", type: "Ogień", types: ["Ogień", "Ziemia"] },
  { id: 323, name: "Camerupt", type: "Ogień", types: ["Ogień", "Ziemia"] },
  { id: 324, name: "Torkoal", type: "Ogień", types: ["Ogień"] },
  { id: 325, name: "Spoink", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 326, name: "Grumpig", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 327, name: "Spinda", type: "Normalny", types: ["Normalny"] },
  { id: 328, name: "Trapinch", type: "Ziemia", types: ["Ziemia"] },
  { id: 329, name: "Vibrava", type: "Ziemia", types: ["Ziemia", "Smok"] },
  { id: 330, name: "Flygon", type: "Ziemia", types: ["Ziemia", "Smok"] },
  { id: 331, name: "Cacnea", type: "Trawa", types: ["Trawa"] },
  { id: 332, name: "Cacturne", type: "Trawa", types: ["Trawa", "Ciemność"] },
  { id: 333, name: "Swablu", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 334, name: "Altaria", type: "Smok", types: ["Smok", "Lot"] },
  { id: 335, name: "Zangoose", type: "Normalny", types: ["Normalny"] },
  { id: 336, name: "Seviper", type: "Trucizna", types: ["Trucizna"] },
  { id: 337, name: "Lunatone", type: "Skała", types: ["Skała", "Psychiczny"] },
  { id: 338, name: "Solrock", type: "Skała", types: ["Skała", "Psychiczny"] },
  { id: 339, name: "Barboach", type: "Woda", types: ["Woda", "Ziemia"] },
  { id: 340, name: "Whiscash", type: "Woda", types: ["Woda", "Ziemia"] },
  { id: 341, name: "Corphish", type: "Woda", types: ["Woda"] },
  { id: 342, name: "Crawdaunt", type: "Woda", types: ["Woda", "Ciemność"] },
  { id: 343, name: "Baltoy", type: "Ziemia", types: ["Ziemia", "Psychiczny"] },
  { id: 344, name: "Claydol", type: "Ziemia", types: ["Ziemia", "Psychiczny"] },
  { id: 345, name: "Lileep", type: "Skała", types: ["Skała", "Trawa"] },
  { id: 346, name: "Cradily", type: "Skała", types: ["Skała", "Trawa"] },
  { id: 347, name: "Anorith", type: "Skała", types: ["Skała", "Robak"] },
  { id: 348, name: "Armaldo", type: "Skała", types: ["Skała", "Robak"] },
  { id: 349, name: "Feebas", type: "Woda", types: ["Woda"] },
  { id: 350, name: "Milotic", type: "Woda", types: ["Woda"] },
  { id: 351, name: "Castform", type: "Normalny", types: ["Normalny"] },
  { id: 352, name: "Kecleon", type: "Normalny", types: ["Normalny"] },
  { id: 353, name: "Shuppet", type: "Duch", types: ["Duch"] },
  { id: 354, name: "Banette", type: "Duch", types: ["Duch"] },
  { id: 355, name: "Duskull", type: "Duch", types: ["Duch"] },
  { id: 356, name: "Dusclops", type: "Duch", types: ["Duch"] },
  { id: 357, name: "Tropius", type: "Trawa", types: ["Trawa", "Lot"] },
  { id: 358, name: "Chimecho", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 359, name: "Absol", type: "Ciemność", types: ["Ciemność"] },
  { id: 360, name: "Wynaut", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 361, name: "Snorunt", type: "Lód", types: ["Lód"] },
  { id: 362, name: "Glalie", type: "Lód", types: ["Lód"] },
  { id: 363, name: "Spheal", type: "Lód", types: ["Lód", "Woda"] },
  { id: 364, name: "Sealeo", type: "Lód", types: ["Lód", "Woda"] },
  { id: 365, name: "Walrein", type: "Lód", types: ["Lód", "Woda"] },
  { id: 366, name: "Clamperl", type: "Woda", types: ["Woda"] },
  { id: 367, name: "Huntail", type: "Woda", types: ["Woda"] },
  { id: 368, name: "Gorebyss", type: "Woda", types: ["Woda"] },
  { id: 369, name: "Relicanth", type: "Woda", types: ["Woda", "Skała"] },
  { id: 370, name: "Luvdisc", type: "Woda", types: ["Woda"] },
  { id: 371, name: "Bagon", type: "Smok", types: ["Smok"] },
  { id: 372, name: "Shelgon", type: "Smok", types: ["Smok"] },
  { id: 373, name: "Salamence", type: "Smok", types: ["Smok", "Lot"] },
  { id: 374, name: "Beldum", type: "Stal", types: ["Stal", "Psychiczny"] },
  { id: 375, name: "Metang", type: "Stal", types: ["Stal", "Psychiczny"] },
  { id: 376, name: "Metagross", type: "Stal", types: ["Stal", "Psychiczny"] },
  { id: 377, name: "Regirock", type: "Skała", types: ["Skała"] },
  { id: 378, name: "Regice", type: "Lód", types: ["Lód"] },
  { id: 379, name: "Registeel", type: "Stal", types: ["Stal"] },
  { id: 380, name: "Latias", type: "Smok", types: ["Smok", "Psychiczny"] },
  { id: 381, name: "Latios", type: "Smok", types: ["Smok", "Psychiczny"] },
  { id: 382, name: "Kyogre", type: "Woda", types: ["Woda"] },
  { id: 383, name: "Groudon", type: "Ziemia", types: ["Ziemia"] },
  { id: 384, name: "Rayquaza", type: "Smok", types: ["Smok", "Lot"] },
  { id: 385, name: "Jirachi", type: "Stal", types: ["Stal", "Psychiczny"] },
  { id: 386, name: "Deoxys-normal", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 387, name: "Turtwig", type: "Trawa", types: ["Trawa"] },
  { id: 388, name: "Grotle", type: "Trawa", types: ["Trawa"] },
  { id: 389, name: "Torterra", type: "Trawa", types: ["Trawa", "Ziemia"] },
  { id: 390, name: "Chimchar", type: "Ogień", types: ["Ogień"] },
  { id: 391, name: "Monferno", type: "Ogień", types: ["Ogień", "Walka"] },
  { id: 392, name: "Infernape", type: "Ogień", types: ["Ogień", "Walka"] },
  { id: 393, name: "Piplup", type: "Woda", types: ["Woda"] },
  { id: 394, name: "Prinplup", type: "Woda", types: ["Woda"] },
  { id: 395, name: "Empoleon", type: "Woda", types: ["Woda", "Stal"] },
  { id: 396, name: "Starly", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 397, name: "Staravia", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 398, name: "Staraptor", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 399, name: "Bidoof", type: "Normalny", types: ["Normalny"] },
  { id: 400, name: "Bibarel", type: "Normalny", types: ["Normalny", "Woda"] },
  { id: 401, name: "Kricketot", type: "Robak", types: ["Robak"] },
  { id: 402, name: "Kricketune", type: "Robak", types: ["Robak"] },
  { id: 403, name: "Shinx", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 404, name: "Luxio", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 405, name: "Luxray", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 406, name: "Budew", type: "Trawa", types: ["Trawa", "Trucizna"] },
  { id: 407, name: "Roserade", type: "Trawa", types: ["Trawa", "Trucizna"] },
  { id: 408, name: "Cranidos", type: "Skała", types: ["Skała"] },
  { id: 409, name: "Rampardos", type: "Skała", types: ["Skała"] },
  { id: 410, name: "Shieldon", type: "Skała", types: ["Skała", "Stal"] },
  { id: 411, name: "Bastiodon", type: "Skała", types: ["Skała", "Stal"] },
  { id: 412, name: "Burmy", type: "Robak", types: ["Robak"] },
  { id: 413, name: "Wormadam-plant", type: "Robak", types: ["Robak", "Trawa"] },
  { id: 414, name: "Mothim", type: "Robak", types: ["Robak", "Lot"] },
  { id: 415, name: "Combee", type: "Robak", types: ["Robak", "Lot"] },
  { id: 416, name: "Vespiquen", type: "Robak", types: ["Robak", "Lot"] },
  { id: 417, name: "Pachirisu", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 418, name: "Buizel", type: "Woda", types: ["Woda"] },
  { id: 419, name: "Floatzel", type: "Woda", types: ["Woda"] },
  { id: 420, name: "Cherubi", type: "Trawa", types: ["Trawa"] },
  { id: 421, name: "Cherrim", type: "Trawa", types: ["Trawa"] },
  { id: 422, name: "Shellos", type: "Woda", types: ["Woda"] },
  { id: 423, name: "Gastrodon", type: "Woda", types: ["Woda", "Ziemia"] },
  { id: 424, name: "Ambipom", type: "Normalny", types: ["Normalny"] },
  { id: 425, name: "Drifloon", type: "Duch", types: ["Duch", "Lot"] },
  { id: 426, name: "Drifblim", type: "Duch", types: ["Duch", "Lot"] },
  { id: 427, name: "Buneary", type: "Normalny", types: ["Normalny"] },
  { id: 428, name: "Lopunny", type: "Normalny", types: ["Normalny"] },
  { id: 429, name: "Mismagius", type: "Duch", types: ["Duch"] },
  { id: 430, name: "Honchkrow", type: "Ciemność", types: ["Ciemność", "Lot"] },
  { id: 431, name: "Glameow", type: "Normalny", types: ["Normalny"] },
  { id: 432, name: "Purugly", type: "Normalny", types: ["Normalny"] },
  { id: 433, name: "Chingling", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 434, name: "Stunky", type: "Trucizna", types: ["Trucizna", "Ciemność"] },
  { id: 435, name: "Skuntank", type: "Trucizna", types: ["Trucizna", "Ciemność"] },
  { id: 436, name: "Bronzor", type: "Stal", types: ["Stal", "Psychiczny"] },
  { id: 437, name: "Bronzong", type: "Stal", types: ["Stal", "Psychiczny"] },
  { id: 438, name: "Bonsly", type: "Skała", types: ["Skała"] },
  { id: 439, name: "Mime-jr", type: "Psychiczny", types: ["Psychiczny", "Baśniowy"] },
  { id: 440, name: "Happiny", type: "Normalny", types: ["Normalny"] },
  { id: 441, name: "Chatot", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 442, name: "Spiritomb", type: "Duch", types: ["Duch", "Ciemność"] },
  { id: 443, name: "Gible", type: "Smok", types: ["Smok", "Ziemia"] },
  { id: 444, name: "Gabite", type: "Smok", types: ["Smok", "Ziemia"] },
  { id: 445, name: "Garchomp", type: "Smok", types: ["Smok", "Ziemia"] },
  { id: 446, name: "Munchlax", type: "Normalny", types: ["Normalny"] },
  { id: 447, name: "Riolu", type: "Walka", types: ["Walka"] },
  { id: 448, name: "Lucario", type: "Walka", types: ["Walka", "Stal"] },
  { id: 449, name: "Hippopotas", type: "Ziemia", types: ["Ziemia"] },
  { id: 450, name: "Hippowdon", type: "Ziemia", types: ["Ziemia"] },
  { id: 451, name: "Skorupi", type: "Trucizna", types: ["Trucizna", "Robak"] },
  { id: 452, name: "Drapion", type: "Trucizna", types: ["Trucizna", "Ciemność"] },
  { id: 453, name: "Croagunk", type: "Trucizna", types: ["Trucizna", "Walka"] },
  { id: 454, name: "Toxicroak", type: "Trucizna", types: ["Trucizna", "Walka"] },
  { id: 455, name: "Carnivine", type: "Trawa", types: ["Trawa"] },
  { id: 456, name: "Finneon", type: "Woda", types: ["Woda"] },
  { id: 457, name: "Lumineon", type: "Woda", types: ["Woda"] },
  { id: 458, name: "Mantyke", type: "Woda", types: ["Woda", "Lot"] },
  { id: 459, name: "Snover", type: "Trawa", types: ["Trawa", "Lód"] },
  { id: 460, name: "Abomasnow", type: "Trawa", types: ["Trawa", "Lód"] },
  { id: 461, name: "Weavile", type: "Ciemność", types: ["Ciemność", "Lód"] },
  { id: 462, name: "Magnezone", type: "Elektryczny", types: ["Elektryczny", "Stal"] },
  { id: 463, name: "Lickilicky", type: "Normalny", types: ["Normalny"] },
  { id: 464, name: "Rhyperior", type: "Ziemia", types: ["Ziemia", "Skała"] },
  { id: 465, name: "Tangrowth", type: "Trawa", types: ["Trawa"] },
  { id: 466, name: "Electivire", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 467, name: "Magmortar", type: "Ogień", types: ["Ogień"] },
  { id: 468, name: "Togekiss", type: "Baśniowy", types: ["Baśniowy", "Lot"] },
  { id: 469, name: "Yanmega", type: "Robak", types: ["Robak", "Lot"] },
  { id: 470, name: "Leafeon", type: "Trawa", types: ["Trawa"] },
  { id: 471, name: "Glaceon", type: "Lód", types: ["Lód"] },
  { id: 472, name: "Gliscor", type: "Ziemia", types: ["Ziemia", "Lot"] },
  { id: 473, name: "Mamoswine", type: "Lód", types: ["Lód", "Ziemia"] },
  { id: 474, name: "Porygon-z", type: "Normalny", types: ["Normalny"] },
  { id: 475, name: "Gallade", type: "Psychiczny", types: ["Psychiczny", "Walka"] },
  { id: 476, name: "Probopass", type: "Skała", types: ["Skała", "Stal"] },
  { id: 477, name: "Dusknoir", type: "Duch", types: ["Duch"] },
  { id: 478, name: "Froslass", type: "Lód", types: ["Lód", "Duch"] },
  { id: 479, name: "Rotom", type: "Elektryczny", types: ["Elektryczny", "Duch"] },
  { id: 480, name: "Uxie", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 481, name: "Mesprit", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 482, name: "Azelf", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 483, name: "Dialga", type: "Stal", types: ["Stal", "Smok"] },
  { id: 484, name: "Palkia", type: "Woda", types: ["Woda", "Smok"] },
  { id: 485, name: "Heatran", type: "Ogień", types: ["Ogień", "Stal"] },
  { id: 486, name: "Regigigas", type: "Normalny", types: ["Normalny"] },
  { id: 487, name: "Giratina-altered", type: "Duch", types: ["Duch", "Smok"] },
  { id: 488, name: "Cresselia", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 489, name: "Phione", type: "Woda", types: ["Woda"] },
  { id: 490, name: "Manaphy", type: "Woda", types: ["Woda"] },
  { id: 491, name: "Darkrai", type: "Ciemność", types: ["Ciemność"] },
  { id: 492, name: "Shaymin-land", type: "Trawa", types: ["Trawa"] },
  { id: 493, name: "Arceus", type: "Normalny", types: ["Normalny"] },
  { id: 494, name: "Victini", type: "Psychiczny", types: ["Psychiczny", "Ogień"] },
  { id: 495, name: "Snivy", type: "Trawa", types: ["Trawa"] },
  { id: 496, name: "Servine", type: "Trawa", types: ["Trawa"] },
  { id: 497, name: "Serperior", type: "Trawa", types: ["Trawa"] },
  { id: 498, name: "Tepig", type: "Ogień", types: ["Ogień"] },
  { id: 499, name: "Pignite", type: "Ogień", types: ["Ogień", "Walka"] },
  { id: 500, name: "Emboar", type: "Ogień", types: ["Ogień", "Walka"] },
  { id: 501, name: "Oshawott", type: "Woda", types: ["Woda"] },
  { id: 502, name: "Dewott", type: "Woda", types: ["Woda"] },
  { id: 503, name: "Samurott", type: "Woda", types: ["Woda"] },
  { id: 504, name: "Patrat", type: "Normalny", types: ["Normalny"] },
  { id: 505, name: "Watchog", type: "Normalny", types: ["Normalny"] },
  { id: 506, name: "Lillipup", type: "Normalny", types: ["Normalny"] },
  { id: 507, name: "Herdier", type: "Normalny", types: ["Normalny"] },
  { id: 508, name: "Stoutland", type: "Normalny", types: ["Normalny"] },
  { id: 509, name: "Purrloin", type: "Ciemność", types: ["Ciemność"] },
  { id: 510, name: "Liepard", type: "Ciemność", types: ["Ciemność"] },
  { id: 511, name: "Pansage", type: "Trawa", types: ["Trawa"] },
  { id: 512, name: "Simisage", type: "Trawa", types: ["Trawa"] },
  { id: 513, name: "Pansear", type: "Ogień", types: ["Ogień"] },
  { id: 514, name: "Simisear", type: "Ogień", types: ["Ogień"] },
  { id: 515, name: "Panpour", type: "Woda", types: ["Woda"] },
  { id: 516, name: "Simipour", type: "Woda", types: ["Woda"] },
  { id: 517, name: "Munna", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 518, name: "Musharna", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 519, name: "Pidove", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 520, name: "Tranquill", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 521, name: "Unfezant", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 522, name: "Blitzle", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 523, name: "Zebstrika", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 524, name: "Roggenrola", type: "Skała", types: ["Skała"] },
  { id: 525, name: "Boldore", type: "Skała", types: ["Skała"] },
  { id: 526, name: "Gigalith", type: "Skała", types: ["Skała"] },
  { id: 527, name: "Woobat", type: "Psychiczny", types: ["Psychiczny", "Lot"] },
  { id: 528, name: "Swoobat", type: "Psychiczny", types: ["Psychiczny", "Lot"] },
  { id: 529, name: "Drilbur", type: "Ziemia", types: ["Ziemia"] },
  { id: 530, name: "Excadrill", type: "Ziemia", types: ["Ziemia", "Stal"] },
  { id: 531, name: "Audino", type: "Normalny", types: ["Normalny"] },
  { id: 532, name: "Timburr", type: "Walka", types: ["Walka"] },
  { id: 533, name: "Gurdurr", type: "Walka", types: ["Walka"] },
  { id: 534, name: "Conkeldurr", type: "Walka", types: ["Walka"] },
  { id: 535, name: "Tympole", type: "Woda", types: ["Woda"] },
  { id: 536, name: "Palpitoad", type: "Woda", types: ["Woda", "Ziemia"] },
  { id: 537, name: "Seismitoad", type: "Woda", types: ["Woda", "Ziemia"] },
  { id: 538, name: "Throh", type: "Walka", types: ["Walka"] },
  { id: 539, name: "Sawk", type: "Walka", types: ["Walka"] },
  { id: 540, name: "Sewaddle", type: "Robak", types: ["Robak", "Trawa"] },
  { id: 541, name: "Swadloon", type: "Robak", types: ["Robak", "Trawa"] },
  { id: 542, name: "Leavanny", type: "Robak", types: ["Robak", "Trawa"] },
  { id: 543, name: "Venipede", type: "Robak", types: ["Robak", "Trucizna"] },
  { id: 544, name: "Whirlipede", type: "Robak", types: ["Robak", "Trucizna"] },
  { id: 545, name: "Scolipede", type: "Robak", types: ["Robak", "Trucizna"] },
  { id: 546, name: "Cottonee", type: "Trawa", types: ["Trawa", "Baśniowy"] },
  { id: 547, name: "Whimsicott", type: "Trawa", types: ["Trawa", "Baśniowy"] },
  { id: 548, name: "Petilil", type: "Trawa", types: ["Trawa"] },
  { id: 549, name: "Lilligant", type: "Trawa", types: ["Trawa"] },
  { id: 550, name: "Basculin-red-striped", type: "Woda", types: ["Woda"] },
  { id: 551, name: "Sandile", type: "Ziemia", types: ["Ziemia", "Ciemność"] },
  { id: 552, name: "Krokorok", type: "Ziemia", types: ["Ziemia", "Ciemność"] },
  { id: 553, name: "Krookodile", type: "Ziemia", types: ["Ziemia", "Ciemność"] },
  { id: 554, name: "Darumaka", type: "Ogień", types: ["Ogień"] },
  { id: 555, name: "Darmanitan-standard", type: "Ogień", types: ["Ogień"] },
  { id: 556, name: "Maractus", type: "Trawa", types: ["Trawa"] },
  { id: 557, name: "Dwebble", type: "Robak", types: ["Robak", "Skała"] },
  { id: 558, name: "Crustle", type: "Robak", types: ["Robak", "Skała"] },
  { id: 559, name: "Scraggy", type: "Ciemność", types: ["Ciemność", "Walka"] },
  { id: 560, name: "Scrafty", type: "Ciemność", types: ["Ciemność", "Walka"] },
  { id: 561, name: "Sigilyph", type: "Psychiczny", types: ["Psychiczny", "Lot"] },
  { id: 562, name: "Yamask", type: "Duch", types: ["Duch"] },
  { id: 563, name: "Cofagrigus", type: "Duch", types: ["Duch"] },
  { id: 564, name: "Tirtouga", type: "Woda", types: ["Woda", "Skała"] },
  { id: 565, name: "Carracosta", type: "Woda", types: ["Woda", "Skała"] },
  { id: 566, name: "Archen", type: "Skała", types: ["Skała", "Lot"] },
  { id: 567, name: "Archeops", type: "Skała", types: ["Skała", "Lot"] },
  { id: 568, name: "Trubbish", type: "Trucizna", types: ["Trucizna"] },
  { id: 569, name: "Garbodor", type: "Trucizna", types: ["Trucizna"] },
  { id: 570, name: "Zorua", type: "Ciemność", types: ["Ciemność"] },
  { id: 571, name: "Zoroark", type: "Ciemność", types: ["Ciemność"] },
  { id: 572, name: "Minccino", type: "Normalny", types: ["Normalny"] },
  { id: 573, name: "Cinccino", type: "Normalny", types: ["Normalny"] },
  { id: 574, name: "Gothita", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 575, name: "Gothorita", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 576, name: "Gothitelle", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 577, name: "Solosis", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 578, name: "Duosion", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 579, name: "Reuniclus", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 580, name: "Ducklett", type: "Woda", types: ["Woda", "Lot"] },
  { id: 581, name: "Swanna", type: "Woda", types: ["Woda", "Lot"] },
  { id: 582, name: "Vanillite", type: "Lód", types: ["Lód"] },
  { id: 583, name: "Vanillish", type: "Lód", types: ["Lód"] },
  { id: 584, name: "Vanilluxe", type: "Lód", types: ["Lód"] },
  { id: 585, name: "Deerling", type: "Normalny", types: ["Normalny", "Trawa"] },
  { id: 586, name: "Sawsbuck", type: "Normalny", types: ["Normalny", "Trawa"] },
  { id: 587, name: "Emolga", type: "Elektryczny", types: ["Elektryczny", "Lot"] },
  { id: 588, name: "Karrablast", type: "Robak", types: ["Robak"] },
  { id: 589, name: "Escavalier", type: "Robak", types: ["Robak", "Stal"] },
  { id: 590, name: "Foongus", type: "Trawa", types: ["Trawa", "Trucizna"] },
  { id: 591, name: "Amoonguss", type: "Trawa", types: ["Trawa", "Trucizna"] },
  { id: 592, name: "Frillish-male", type: "Woda", types: ["Woda", "Duch"] },
  { id: 593, name: "Jellicent-male", type: "Woda", types: ["Woda", "Duch"] },
  { id: 594, name: "Alomomola", type: "Woda", types: ["Woda"] },
  { id: 595, name: "Joltik", type: "Robak", types: ["Robak", "Elektryczny"] },
  { id: 596, name: "Galvantula", type: "Robak", types: ["Robak", "Elektryczny"] },
  { id: 597, name: "Ferroseed", type: "Trawa", types: ["Trawa", "Stal"] },
  { id: 598, name: "Ferrothorn", type: "Trawa", types: ["Trawa", "Stal"] },
  { id: 599, name: "Klink", type: "Stal", types: ["Stal"] },
  { id: 600, name: "Klang", type: "Stal", types: ["Stal"] },
  { id: 601, name: "Klinklang", type: "Stal", types: ["Stal"] },
  { id: 602, name: "Tynamo", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 603, name: "Eelektrik", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 604, name: "Eelektross", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 605, name: "Elgyem", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 606, name: "Beheeyem", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 607, name: "Litwick", type: "Duch", types: ["Duch", "Ogień"] },
  { id: 608, name: "Lampent", type: "Duch", types: ["Duch", "Ogień"] },
  { id: 609, name: "Chandelure", type: "Duch", types: ["Duch", "Ogień"] },
  { id: 610, name: "Axew", type: "Smok", types: ["Smok"] },
  { id: 611, name: "Fraxure", type: "Smok", types: ["Smok"] },
  { id: 612, name: "Haxorus", type: "Smok", types: ["Smok"] },
  { id: 613, name: "Cubchoo", type: "Lód", types: ["Lód"] },
  { id: 614, name: "Beartic", type: "Lód", types: ["Lód"] },
  { id: 615, name: "Cryogonal", type: "Lód", types: ["Lód"] },
  { id: 616, name: "Shelmet", type: "Robak", types: ["Robak"] },
  { id: 617, name: "Accelgor", type: "Robak", types: ["Robak"] },
  { id: 618, name: "Stunfisk", type: "Ziemia", types: ["Ziemia", "Elektryczny"] },
  { id: 619, name: "Mienfoo", type: "Walka", types: ["Walka"] },
  { id: 620, name: "Mienshao", type: "Walka", types: ["Walka"] },
  { id: 621, name: "Druddigon", type: "Smok", types: ["Smok"] },
  { id: 622, name: "Golett", type: "Ziemia", types: ["Ziemia", "Duch"] },
  { id: 623, name: "Golurk", type: "Ziemia", types: ["Ziemia", "Duch"] },
  { id: 624, name: "Pawniard", type: "Ciemność", types: ["Ciemność", "Stal"] },
  { id: 625, name: "Bisharp", type: "Ciemność", types: ["Ciemność", "Stal"] },
  { id: 626, name: "Bouffalant", type: "Normalny", types: ["Normalny"] },
  { id: 627, name: "Rufflet", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 628, name: "Braviary", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 629, name: "Vullaby", type: "Ciemność", types: ["Ciemność", "Lot"] },
  { id: 630, name: "Mandibuzz", type: "Ciemność", types: ["Ciemność", "Lot"] },
  { id: 631, name: "Heatmor", type: "Ogień", types: ["Ogień"] },
  { id: 632, name: "Durant", type: "Robak", types: ["Robak", "Stal"] },
  { id: 633, name: "Deino", type: "Ciemność", types: ["Ciemność", "Smok"] },
  { id: 634, name: "Zweilous", type: "Ciemność", types: ["Ciemność", "Smok"] },
  { id: 635, name: "Hydreigon", type: "Ciemność", types: ["Ciemność", "Smok"] },
  { id: 636, name: "Larvesta", type: "Robak", types: ["Robak", "Ogień"] },
  { id: 637, name: "Volcarona", type: "Robak", types: ["Robak", "Ogień"] },
  { id: 638, name: "Cobalion", type: "Stal", types: ["Stal", "Walka"] },
  { id: 639, name: "Terrakion", type: "Skała", types: ["Skała", "Walka"] },
  { id: 640, name: "Virizion", type: "Trawa", types: ["Trawa", "Walka"] },
  { id: 641, name: "Tornadus-incarnate", type: "Lot", types: ["Lot"] },
  { id: 642, name: "Thundurus-incarnate", type: "Elektryczny", types: ["Elektryczny", "Lot"] },
  { id: 643, name: "Reshiram", type: "Smok", types: ["Smok", "Ogień"] },
  { id: 644, name: "Zekrom", type: "Smok", types: ["Smok", "Elektryczny"] },
  { id: 645, name: "Landorus-incarnate", type: "Ziemia", types: ["Ziemia", "Lot"] },
  { id: 646, name: "Kyurem", type: "Smok", types: ["Smok", "Lód"] },
  { id: 647, name: "Keldeo-ordinary", type: "Woda", types: ["Woda", "Walka"] },
  { id: 648, name: "Meloetta-aria", type: "Normalny", types: ["Normalny", "Psychiczny"] },
  { id: 649, name: "Genesect", type: "Robak", types: ["Robak", "Stal"] },
  { id: 650, name: "Chespin", type: "Trawa", types: ["Trawa"] },
  { id: 651, name: "Quilladin", type: "Trawa", types: ["Trawa"] },
  { id: 652, name: "Chesnaught", type: "Trawa", types: ["Trawa", "Walka"] },
  { id: 653, name: "Fennekin", type: "Ogień", types: ["Ogień"] },
  { id: 654, name: "Braixen", type: "Ogień", types: ["Ogień"] },
  { id: 655, name: "Delphox", type: "Ogień", types: ["Ogień", "Psychiczny"] },
  { id: 656, name: "Froakie", type: "Woda", types: ["Woda"] },
  { id: 657, name: "Frogadier", type: "Woda", types: ["Woda"] },
  { id: 658, name: "Greninja", type: "Woda", types: ["Woda", "Ciemność"] },
  { id: 659, name: "Bunnelby", type: "Normalny", types: ["Normalny"] },
  { id: 660, name: "Diggersby", type: "Normalny", types: ["Normalny", "Ziemia"] },
  { id: 661, name: "Fletchling", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 662, name: "Fletchinder", type: "Ogień", types: ["Ogień", "Lot"] },
  { id: 663, name: "Talonflame", type: "Ogień", types: ["Ogień", "Lot"] },
  { id: 664, name: "Scatterbug", type: "Robak", types: ["Robak"] },
  { id: 665, name: "Spewpa", type: "Robak", types: ["Robak"] },
  { id: 666, name: "Vivillon", type: "Robak", types: ["Robak", "Lot"] },
  { id: 667, name: "Litleo", type: "Ogień", types: ["Ogień", "Normalny"] },
  { id: 668, name: "Pyroar-male", type: "Ogień", types: ["Ogień", "Normalny"] },
  { id: 669, name: "Flabebe", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 670, name: "Floette", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 671, name: "Florges", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 672, name: "Skiddo", type: "Trawa", types: ["Trawa"] },
  { id: 673, name: "Gogoat", type: "Trawa", types: ["Trawa"] },
  { id: 674, name: "Pancham", type: "Walka", types: ["Walka"] },
  { id: 675, name: "Pangoro", type: "Walka", types: ["Walka", "Ciemność"] },
  { id: 676, name: "Furfrou", type: "Normalny", types: ["Normalny"] },
  { id: 677, name: "Espurr", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 678, name: "Meowstic-male", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 679, name: "Honedge", type: "Stal", types: ["Stal", "Duch"] },
  { id: 680, name: "Doublade", type: "Stal", types: ["Stal", "Duch"] },
  { id: 681, name: "Aegislash-shield", type: "Stal", types: ["Stal", "Duch"] },
  { id: 682, name: "Spritzee", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 683, name: "Aromatisse", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 684, name: "Swirlix", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 685, name: "Slurpuff", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 686, name: "Inkay", type: "Ciemność", types: ["Ciemność", "Psychiczny"] },
  { id: 687, name: "Malamar", type: "Ciemność", types: ["Ciemność", "Psychiczny"] },
  { id: 688, name: "Binacle", type: "Skała", types: ["Skała", "Woda"] },
  { id: 689, name: "Barbaracle", type: "Skała", types: ["Skała", "Woda"] },
  { id: 690, name: "Skrelp", type: "Trucizna", types: ["Trucizna", "Woda"] },
  { id: 691, name: "Dragalge", type: "Trucizna", types: ["Trucizna", "Smok"] },
  { id: 692, name: "Clauncher", type: "Woda", types: ["Woda"] },
  { id: 693, name: "Clawitzer", type: "Woda", types: ["Woda"] },
  { id: 694, name: "Helioptile", type: "Elektryczny", types: ["Elektryczny", "Normalny"] },
  { id: 695, name: "Heliolisk", type: "Elektryczny", types: ["Elektryczny", "Normalny"] },
  { id: 696, name: "Tyrunt", type: "Skała", types: ["Skała", "Smok"] },
  { id: 697, name: "Tyrantrum", type: "Skała", types: ["Skała", "Smok"] },
  { id: 698, name: "Amaura", type: "Skała", types: ["Skała", "Lód"] },
  { id: 699, name: "Aurorus", type: "Skała", types: ["Skała", "Lód"] },
  { id: 700, name: "Sylveon", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 701, name: "Hawlucha", type: "Walka", types: ["Walka", "Lot"] },
  { id: 702, name: "Dedenne", type: "Elektryczny", types: ["Elektryczny", "Baśniowy"] },
  { id: 703, name: "Carbink", type: "Skała", types: ["Skała", "Baśniowy"] },
  { id: 704, name: "Goomy", type: "Smok", types: ["Smok"] },
  { id: 705, name: "Sliggoo", type: "Smok", types: ["Smok"] },
  { id: 706, name: "Goodra", type: "Smok", types: ["Smok"] },
  { id: 707, name: "Klefki", type: "Stal", types: ["Stal", "Baśniowy"] },
  { id: 708, name: "Phantump", type: "Duch", types: ["Duch", "Trawa"] },
  { id: 709, name: "Trevenant", type: "Duch", types: ["Duch", "Trawa"] },
  { id: 710, name: "Pumpkaboo-average", type: "Duch", types: ["Duch", "Trawa"] },
  { id: 711, name: "Gourgeist-average", type: "Duch", types: ["Duch", "Trawa"] },
  { id: 712, name: "Bergmite", type: "Lód", types: ["Lód"] },
  { id: 713, name: "Avalugg", type: "Lód", types: ["Lód"] },
  { id: 714, name: "Noibat", type: "Lot", types: ["Lot", "Smok"] },
  { id: 715, name: "Noivern", type: "Lot", types: ["Lot", "Smok"] },
  { id: 716, name: "Xerneas", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 717, name: "Yveltal", type: "Ciemność", types: ["Ciemność", "Lot"] },
  { id: 718, name: "Zygarde-50", type: "Smok", types: ["Smok", "Ziemia"] },
  { id: 719, name: "Diancie", type: "Skała", types: ["Skała", "Baśniowy"] },
  { id: 720, name: "Hoopa", type: "Psychiczny", types: ["Psychiczny", "Duch"] },
  { id: 721, name: "Volcanion", type: "Ogień", types: ["Ogień", "Woda"] },
  { id: 722, name: "Rowlet", type: "Trawa", types: ["Trawa", "Lot"] },
  { id: 723, name: "Dartrix", type: "Trawa", types: ["Trawa", "Lot"] },
  { id: 724, name: "Decidueye", type: "Trawa", types: ["Trawa", "Duch"] },
  { id: 725, name: "Litten", type: "Ogień", types: ["Ogień"] },
  { id: 726, name: "Torracat", type: "Ogień", types: ["Ogień"] },
  { id: 727, name: "Incineroar", type: "Ogień", types: ["Ogień", "Ciemność"] },
  { id: 728, name: "Popplio", type: "Woda", types: ["Woda"] },
  { id: 729, name: "Brionne", type: "Woda", types: ["Woda"] },
  { id: 730, name: "Primarina", type: "Woda", types: ["Woda", "Baśniowy"] },
  { id: 731, name: "Pikipek", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 732, name: "Trumbeak", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 733, name: "Toucannon", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 734, name: "Yungoos", type: "Normalny", types: ["Normalny"] },
  { id: 735, name: "Gumshoos", type: "Normalny", types: ["Normalny"] },
  { id: 736, name: "Grubbin", type: "Robak", types: ["Robak"] },
  { id: 737, name: "Charjabug", type: "Robak", types: ["Robak", "Elektryczny"] },
  { id: 738, name: "Vikavolt", type: "Robak", types: ["Robak", "Elektryczny"] },
  { id: 739, name: "Crabrawler", type: "Walka", types: ["Walka"] },
  { id: 740, name: "Crabominable", type: "Walka", types: ["Walka", "Lód"] },
  { id: 741, name: "Oricorio-baile", type: "Ogień", types: ["Ogień", "Lot"] },
  { id: 742, name: "Cutiefly", type: "Robak", types: ["Robak", "Baśniowy"] },
  { id: 743, name: "Ribombee", type: "Robak", types: ["Robak", "Baśniowy"] },
  { id: 744, name: "Rockruff", type: "Skała", types: ["Skała"] },
  { id: 745, name: "Lycanroc-midday", type: "Skała", types: ["Skała"] },
  { id: 746, name: "Wishiwashi-solo", type: "Woda", types: ["Woda"] },
  { id: 747, name: "Mareanie", type: "Trucizna", types: ["Trucizna", "Woda"] },
  { id: 748, name: "Toxapex", type: "Trucizna", types: ["Trucizna", "Woda"] },
  { id: 749, name: "Mudbray", type: "Ziemia", types: ["Ziemia"] },
  { id: 750, name: "Mudsdale", type: "Ziemia", types: ["Ziemia"] },
  { id: 751, name: "Dewpider", type: "Woda", types: ["Woda", "Robak"] },
  { id: 752, name: "Araquanid", type: "Woda", types: ["Woda", "Robak"] },
  { id: 753, name: "Fomantis", type: "Trawa", types: ["Trawa"] },
  { id: 754, name: "Lurantis", type: "Trawa", types: ["Trawa"] },
  { id: 755, name: "Morelull", type: "Trawa", types: ["Trawa", "Baśniowy"] },
  { id: 756, name: "Shiinotic", type: "Trawa", types: ["Trawa", "Baśniowy"] },
  { id: 757, name: "Salandit", type: "Trucizna", types: ["Trucizna", "Ogień"] },
  { id: 758, name: "Salazzle", type: "Trucizna", types: ["Trucizna", "Ogień"] },
  { id: 759, name: "Stufful", type: "Normalny", types: ["Normalny", "Walka"] },
  { id: 760, name: "Bewear", type: "Normalny", types: ["Normalny", "Walka"] },
  { id: 761, name: "Bounsweet", type: "Trawa", types: ["Trawa"] },
  { id: 762, name: "Steenee", type: "Trawa", types: ["Trawa"] },
  { id: 763, name: "Tsareena", type: "Trawa", types: ["Trawa"] },
  { id: 764, name: "Comfey", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 765, name: "Oranguru", type: "Normalny", types: ["Normalny", "Psychiczny"] },
  { id: 766, name: "Passimian", type: "Walka", types: ["Walka"] },
  { id: 767, name: "Wimpod", type: "Robak", types: ["Robak", "Woda"] },
  { id: 768, name: "Golisopod", type: "Robak", types: ["Robak", "Woda"] },
  { id: 769, name: "Sandygast", type: "Duch", types: ["Duch", "Ziemia"] },
  { id: 770, name: "Palossand", type: "Duch", types: ["Duch", "Ziemia"] },
  { id: 771, name: "Pyukumuku", type: "Woda", types: ["Woda"] },
  { id: 772, name: "Type-null", type: "Normalny", types: ["Normalny"] },
  { id: 773, name: "Silvally", type: "Normalny", types: ["Normalny"] },
  { id: 774, name: "Minior-red-meteor", type: "Skała", types: ["Skała", "Lot"] },
  { id: 775, name: "Komala", type: "Normalny", types: ["Normalny"] },
  { id: 776, name: "Turtonator", type: "Ogień", types: ["Ogień", "Smok"] },
  { id: 777, name: "Togedemaru", type: "Elektryczny", types: ["Elektryczny", "Stal"] },
  { id: 778, name: "Mimikyu-disguised", type: "Duch", types: ["Duch", "Baśniowy"] },
  { id: 779, name: "Bruxish", type: "Woda", types: ["Woda", "Psychiczny"] },
  { id: 780, name: "Drampa", type: "Normalny", types: ["Normalny", "Smok"] },
  { id: 781, name: "Dhelmise", type: "Duch", types: ["Duch", "Trawa"] },
  { id: 782, name: "Jangmo-o", type: "Smok", types: ["Smok"] },
  { id: 783, name: "Hakamo-o", type: "Smok", types: ["Smok", "Walka"] },
  { id: 784, name: "Kommo-o", type: "Smok", types: ["Smok", "Walka"] },
  { id: 785, name: "Tapu-koko", type: "Elektryczny", types: ["Elektryczny", "Baśniowy"] },
  { id: 786, name: "Tapu-lele", type: "Psychiczny", types: ["Psychiczny", "Baśniowy"] },
  { id: 787, name: "Tapu-bulu", type: "Trawa", types: ["Trawa", "Baśniowy"] },
  { id: 788, name: "Tapu-fini", type: "Woda", types: ["Woda", "Baśniowy"] },
  { id: 789, name: "Cosmog", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 790, name: "Cosmoem", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 791, name: "Solgaleo", type: "Psychiczny", types: ["Psychiczny", "Stal"] },
  { id: 792, name: "Lunala", type: "Psychiczny", types: ["Psychiczny", "Duch"] },
  { id: 793, name: "Nihilego", type: "Skała", types: ["Skała", "Trucizna"] },
  { id: 794, name: "Buzzwole", type: "Robak", types: ["Robak", "Walka"] },
  { id: 795, name: "Pheromosa", type: "Robak", types: ["Robak", "Walka"] },
  { id: 796, name: "Xurkitree", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 797, name: "Celesteela", type: "Stal", types: ["Stal", "Lot"] },
  { id: 798, name: "Kartana", type: "Trawa", types: ["Trawa", "Stal"] },
  { id: 799, name: "Guzzlord", type: "Ciemność", types: ["Ciemność", "Smok"] },
  { id: 800, name: "Necrozma", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 801, name: "Magearna", type: "Stal", types: ["Stal", "Baśniowy"] },
  { id: 802, name: "Marshadow", type: "Walka", types: ["Walka", "Duch"] },
  { id: 803, name: "Poipole", type: "Trucizna", types: ["Trucizna"] },
  { id: 804, name: "Naganadel", type: "Trucizna", types: ["Trucizna", "Smok"] },
  { id: 805, name: "Stakataka", type: "Skała", types: ["Skała", "Stal"] },
  { id: 806, name: "Blacephalon", type: "Ogień", types: ["Ogień", "Duch"] },
  { id: 807, name: "Zeraora", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 808, name: "Meltan", type: "Stal", types: ["Stal"] },
  { id: 809, name: "Melmetal", type: "Stal", types: ["Stal"] },
  { id: 810, name: "Grookey", type: "Trawa", types: ["Trawa"] },
  { id: 811, name: "Thwackey", type: "Trawa", types: ["Trawa"] },
  { id: 812, name: "Rillaboom", type: "Trawa", types: ["Trawa"] },
  { id: 813, name: "Scorbunny", type: "Ogień", types: ["Ogień"] },
  { id: 814, name: "Raboot", type: "Ogień", types: ["Ogień"] },
  { id: 815, name: "Cinderace", type: "Ogień", types: ["Ogień"] },
  { id: 816, name: "Sobble", type: "Woda", types: ["Woda"] },
  { id: 817, name: "Drizzile", type: "Woda", types: ["Woda"] },
  { id: 818, name: "Inteleon", type: "Woda", types: ["Woda"] },
  { id: 819, name: "Skwovet", type: "Normalny", types: ["Normalny"] },
  { id: 820, name: "Greedent", type: "Normalny", types: ["Normalny"] },
  { id: 821, name: "Rookidee", type: "Lot", types: ["Lot"] },
  { id: 822, name: "Corvisquire", type: "Lot", types: ["Lot"] },
  { id: 823, name: "Corviknight", type: "Lot", types: ["Lot", "Stal"] },
  { id: 824, name: "Blipbug", type: "Robak", types: ["Robak"] },
  { id: 825, name: "Dottler", type: "Robak", types: ["Robak", "Psychiczny"] },
  { id: 826, name: "Orbeetle", type: "Robak", types: ["Robak", "Psychiczny"] },
  { id: 827, name: "Nickit", type: "Ciemność", types: ["Ciemność"] },
  { id: 828, name: "Thievul", type: "Ciemność", types: ["Ciemność"] },
  { id: 829, name: "Gossifleur", type: "Trawa", types: ["Trawa"] },
  { id: 830, name: "Eldegoss", type: "Trawa", types: ["Trawa"] },
  { id: 831, name: "Wooloo", type: "Normalny", types: ["Normalny"] },
  { id: 832, name: "Dubwool", type: "Normalny", types: ["Normalny"] },
  { id: 833, name: "Chewtle", type: "Woda", types: ["Woda"] },
  { id: 834, name: "Drednaw", type: "Woda", types: ["Woda", "Skała"] },
  { id: 835, name: "Yamper", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 836, name: "Boltund", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 837, name: "Rolycoly", type: "Skała", types: ["Skała"] },
  { id: 838, name: "Carkol", type: "Skała", types: ["Skała", "Ogień"] },
  { id: 839, name: "Coalossal", type: "Skała", types: ["Skała", "Ogień"] },
  { id: 840, name: "Applin", type: "Trawa", types: ["Trawa", "Smok"] },
  { id: 841, name: "Flapple", type: "Trawa", types: ["Trawa", "Smok"] },
  { id: 842, name: "Appletun", type: "Trawa", types: ["Trawa", "Smok"] },
  { id: 843, name: "Silicobra", type: "Ziemia", types: ["Ziemia"] },
  { id: 844, name: "Sandaconda", type: "Ziemia", types: ["Ziemia"] },
  { id: 845, name: "Cramorant", type: "Lot", types: ["Lot", "Woda"] },
  { id: 846, name: "Arrokuda", type: "Woda", types: ["Woda"] },
  { id: 847, name: "Barraskewda", type: "Woda", types: ["Woda"] },
  { id: 848, name: "Toxel", type: "Elektryczny", types: ["Elektryczny", "Trucizna"] },
  { id: 849, name: "Toxtricity-amped", type: "Elektryczny", types: ["Elektryczny", "Trucizna"] },
  { id: 850, name: "Sizzlipede", type: "Ogień", types: ["Ogień", "Robak"] },
  { id: 851, name: "Centiskorch", type: "Ogień", types: ["Ogień", "Robak"] },
  { id: 852, name: "Clobbopus", type: "Walka", types: ["Walka"] },
  { id: 853, name: "Grapploct", type: "Walka", types: ["Walka"] },
  { id: 854, name: "Sinistea", type: "Duch", types: ["Duch"] },
  { id: 855, name: "Polteageist", type: "Duch", types: ["Duch"] },
  { id: 856, name: "Hatenna", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 857, name: "Hattrem", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 858, name: "Hatterene", type: "Psychiczny", types: ["Psychiczny", "Baśniowy"] },
  { id: 859, name: "Impidimp", type: "Ciemność", types: ["Ciemność", "Baśniowy"] },
  { id: 860, name: "Morgrem", type: "Ciemność", types: ["Ciemność", "Baśniowy"] },
  { id: 861, name: "Grimmsnarl", type: "Ciemność", types: ["Ciemność", "Baśniowy"] },
  { id: 862, name: "Obstagoon", type: "Ciemność", types: ["Ciemność", "Normalny"] },
  { id: 863, name: "Perrserker", type: "Stal", types: ["Stal"] },
  { id: 864, name: "Cursola", type: "Duch", types: ["Duch"] },
  { id: 865, name: "Sirfetchd", type: "Walka", types: ["Walka"] },
  { id: 866, name: "Mr-rime", type: "Lód", types: ["Lód", "Psychiczny"] },
  { id: 867, name: "Runerigus", type: "Ziemia", types: ["Ziemia", "Duch"] },
  { id: 868, name: "Milcery", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 869, name: "Alcremie", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 870, name: "Falinks", type: "Walka", types: ["Walka"] },
  { id: 871, name: "Pincurchin", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 872, name: "Snom", type: "Lód", types: ["Lód", "Robak"] },
  { id: 873, name: "Frosmoth", type: "Lód", types: ["Lód", "Robak"] },
  { id: 874, name: "Stonjourner", type: "Skała", types: ["Skała"] },
  { id: 875, name: "Eiscue-ice", type: "Lód", types: ["Lód"] },
  { id: 876, name: "Indeedee-male", type: "Psychiczny", types: ["Psychiczny", "Normalny"] },
  { id: 877, name: "Morpeko-full-belly", type: "Elektryczny", types: ["Elektryczny", "Ciemność"] },
  { id: 878, name: "Cufant", type: "Stal", types: ["Stal"] },
  { id: 879, name: "Copperajah", type: "Stal", types: ["Stal"] },
  { id: 880, name: "Dracozolt", type: "Elektryczny", types: ["Elektryczny", "Smok"] },
  { id: 881, name: "Arctozolt", type: "Elektryczny", types: ["Elektryczny", "Lód"] },
  { id: 882, name: "Dracovish", type: "Woda", types: ["Woda", "Smok"] },
  { id: 883, name: "Arctovish", type: "Woda", types: ["Woda", "Lód"] },
  { id: 884, name: "Duraludon", type: "Stal", types: ["Stal", "Smok"] },
  { id: 885, name: "Dreepy", type: "Smok", types: ["Smok", "Duch"] },
  { id: 886, name: "Drakloak", type: "Smok", types: ["Smok", "Duch"] },
  { id: 887, name: "Dragapult", type: "Smok", types: ["Smok", "Duch"] },
  { id: 888, name: "Zacian", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 889, name: "Zamazenta", type: "Walka", types: ["Walka"] },
  { id: 890, name: "Eternatus", type: "Trucizna", types: ["Trucizna", "Smok"] },
  { id: 891, name: "Kubfu", type: "Walka", types: ["Walka"] },
  { id: 892, name: "Urshifu-single-strike", type: "Walka", types: ["Walka", "Ciemność"] },
  { id: 893, name: "Zarude", type: "Ciemność", types: ["Ciemność", "Trawa"] },
  { id: 894, name: "Regieleki", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 895, name: "Regidrago", type: "Smok", types: ["Smok"] },
  { id: 896, name: "Glastrier", type: "Lód", types: ["Lód"] },
  { id: 897, name: "Spectrier", type: "Duch", types: ["Duch"] },
  { id: 898, name: "Calyrex", type: "Psychiczny", types: ["Psychiczny", "Trawa"] },
  { id: 899, name: "Wyrdeer", type: "Normalny", types: ["Normalny", "Psychiczny"] },
  { id: 900, name: "Kleavor", type: "Robak", types: ["Robak", "Skała"] },
  { id: 901, name: "Ursaluna", type: "Ziemia", types: ["Ziemia", "Normalny"] },
  { id: 902, name: "Basculegion-male", type: "Woda", types: ["Woda", "Duch"] },
  { id: 903, name: "Sneasler", type: "Walka", types: ["Walka", "Trucizna"] },
  { id: 904, name: "Overqwil", type: "Ciemność", types: ["Ciemność", "Trucizna"] },
  { id: 905, name: "Enamorus-incarnate", type: "Baśniowy", types: ["Baśniowy", "Lot"] },
  { id: 906, name: "Sprigatito", type: "Trawa", types: ["Trawa"] },
  { id: 907, name: "Floragato", type: "Trawa", types: ["Trawa"] },
  { id: 908, name: "Meowscarada", type: "Trawa", types: ["Trawa", "Ciemność"] },
  { id: 909, name: "Fuecoco", type: "Ogień", types: ["Ogień"] },
  { id: 910, name: "Crocalor", type: "Ogień", types: ["Ogień"] },
  { id: 911, name: "Skeledirge", type: "Ogień", types: ["Ogień", "Duch"] },
  { id: 912, name: "Quaxly", type: "Woda", types: ["Woda"] },
  { id: 913, name: "Quaxwell", type: "Woda", types: ["Woda"] },
  { id: 914, name: "Quaquaval", type: "Woda", types: ["Woda", "Walka"] },
  { id: 915, name: "Lechonk", type: "Normalny", types: ["Normalny"] },
  { id: 916, name: "Oinkologne-male", type: "Normalny", types: ["Normalny"] },
  { id: 917, name: "Tarountula", type: "Robak", types: ["Robak"] },
  { id: 918, name: "Spidops", type: "Robak", types: ["Robak"] },
  { id: 919, name: "Nymble", type: "Robak", types: ["Robak"] },
  { id: 920, name: "Lokix", type: "Robak", types: ["Robak", "Ciemność"] },
  { id: 921, name: "Pawmi", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 922, name: "Pawmo", type: "Elektryczny", types: ["Elektryczny", "Walka"] },
  { id: 923, name: "Pawmot", type: "Elektryczny", types: ["Elektryczny", "Walka"] },
  { id: 924, name: "Tandemaus", type: "Normalny", types: ["Normalny"] },
  { id: 925, name: "Maushold-family-of-four", type: "Normalny", types: ["Normalny"] },
  { id: 926, name: "Fidough", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 927, name: "Dachsbun", type: "Baśniowy", types: ["Baśniowy"] },
  { id: 928, name: "Smoliv", type: "Trawa", types: ["Trawa", "Normalny"] },
  { id: 929, name: "Dolliv", type: "Trawa", types: ["Trawa", "Normalny"] },
  { id: 930, name: "Arboliva", type: "Trawa", types: ["Trawa", "Normalny"] },
  { id: 931, name: "Squawkabilly-green-plumage", type: "Normalny", types: ["Normalny", "Lot"] },
  { id: 932, name: "Nacli", type: "Skała", types: ["Skała"] },
  { id: 933, name: "Naclstack", type: "Skała", types: ["Skała"] },
  { id: 934, name: "Garganacl", type: "Skała", types: ["Skała"] },
  { id: 935, name: "Charcadet", type: "Ogień", types: ["Ogień"] },
  { id: 936, name: "Armarouge", type: "Ogień", types: ["Ogień", "Psychiczny"] },
  { id: 937, name: "Ceruledge", type: "Ogień", types: ["Ogień", "Duch"] },
  { id: 938, name: "Tadbulb", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 939, name: "Bellibolt", type: "Elektryczny", types: ["Elektryczny"] },
  { id: 940, name: "Wattrel", type: "Elektryczny", types: ["Elektryczny", "Lot"] },
  { id: 941, name: "Kilowattrel", type: "Elektryczny", types: ["Elektryczny", "Lot"] },
  { id: 942, name: "Maschiff", type: "Ciemność", types: ["Ciemność"] },
  { id: 943, name: "Mabosstiff", type: "Ciemność", types: ["Ciemność"] },
  { id: 944, name: "Shroodle", type: "Trucizna", types: ["Trucizna", "Normalny"] },
  { id: 945, name: "Grafaiai", type: "Trucizna", types: ["Trucizna", "Normalny"] },
  { id: 946, name: "Bramblin", type: "Trawa", types: ["Trawa", "Duch"] },
  { id: 947, name: "Brambleghast", type: "Trawa", types: ["Trawa", "Duch"] },
  { id: 948, name: "Toedscool", type: "Ziemia", types: ["Ziemia", "Trawa"] },
  { id: 949, name: "Toedscruel", type: "Ziemia", types: ["Ziemia", "Trawa"] },
  { id: 950, name: "Klawf", type: "Skała", types: ["Skała"] },
  { id: 951, name: "Capsakid", type: "Trawa", types: ["Trawa"] },
  { id: 952, name: "Scovillain", type: "Trawa", types: ["Trawa", "Ogień"] },
  { id: 953, name: "Rellor", type: "Robak", types: ["Robak"] },
  { id: 954, name: "Rabsca", type: "Robak", types: ["Robak", "Psychiczny"] },
  { id: 955, name: "Flittle", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 956, name: "Espathra", type: "Psychiczny", types: ["Psychiczny"] },
  { id: 957, name: "Tinkatink", type: "Baśniowy", types: ["Baśniowy", "Stal"] },
  { id: 958, name: "Tinkatuff", type: "Baśniowy", types: ["Baśniowy", "Stal"] },
  { id: 959, name: "Tinkaton", type: "Baśniowy", types: ["Baśniowy", "Stal"] },
  { id: 960, name: "Wiglett", type: "Woda", types: ["Woda"] },
  { id: 961, name: "Wugtrio", type: "Woda", types: ["Woda"] },
  { id: 962, name: "Bombirdier", type: "Lot", types: ["Lot", "Ciemność"] },
  { id: 963, name: "Finizen", type: "Woda", types: ["Woda"] },
  { id: 964, name: "Palafin-zero", type: "Woda", types: ["Woda"] },
  { id: 965, name: "Varoom", type: "Stal", types: ["Stal", "Trucizna"] },
  { id: 966, name: "Revavroom", type: "Stal", types: ["Stal", "Trucizna"] },
  { id: 967, name: "Cyclizar", type: "Smok", types: ["Smok", "Normalny"] },
  { id: 968, name: "Orthworm", type: "Stal", types: ["Stal"] },
  { id: 969, name: "Glimmet", type: "Skała", types: ["Skała", "Trucizna"] },
  { id: 970, name: "Glimmora", type: "Skała", types: ["Skała", "Trucizna"] },
  { id: 971, name: "Greavard", type: "Duch", types: ["Duch"] },
  { id: 972, name: "Houndstone", type: "Duch", types: ["Duch"] },
  { id: 973, name: "Flamigo", type: "Lot", types: ["Lot", "Walka"] },
  { id: 974, name: "Cetoddle", type: "Lód", types: ["Lód"] },
  { id: 975, name: "Cetitan", type: "Lód", types: ["Lód"] },
  { id: 976, name: "Veluza", type: "Woda", types: ["Woda", "Psychiczny"] },
  { id: 977, name: "Dondozo", type: "Woda", types: ["Woda"] },
  { id: 978, name: "Tatsugiri-curly", type: "Smok", types: ["Smok", "Woda"] },
  { id: 979, name: "Annihilape", type: "Walka", types: ["Walka", "Duch"] },
  { id: 980, name: "Clodsire", type: "Trucizna", types: ["Trucizna", "Ziemia"] },
  { id: 981, name: "Farigiraf", type: "Normalny", types: ["Normalny", "Psychiczny"] },
  { id: 982, name: "Dudunsparce-two-segment", type: "Normalny", types: ["Normalny"] },
  { id: 983, name: "Kingambit", type: "Ciemność", types: ["Ciemność", "Stal"] },
  { id: 984, name: "Great-tusk", type: "Ziemia", types: ["Ziemia", "Walka"] },
  { id: 985, name: "Scream-tail", type: "Baśniowy", types: ["Baśniowy", "Psychiczny"] },
  { id: 986, name: "Brute-bonnet", type: "Trawa", types: ["Trawa", "Ciemność"] },
  { id: 987, name: "Flutter-mane", type: "Duch", types: ["Duch", "Baśniowy"] },
  { id: 988, name: "Slither-wing", type: "Robak", types: ["Robak", "Walka"] },
  { id: 989, name: "Sandy-shocks", type: "Elektryczny", types: ["Elektryczny", "Ziemia"] },
  { id: 990, name: "Iron-treads", type: "Ziemia", types: ["Ziemia", "Stal"] },
  { id: 991, name: "Iron-bundle", type: "Lód", types: ["Lód", "Woda"] },
  { id: 992, name: "Iron-hands", type: "Walka", types: ["Walka", "Elektryczny"] },
  { id: 993, name: "Iron-jugulis", type: "Ciemność", types: ["Ciemność", "Lot"] },
  { id: 994, name: "Iron-moth", type: "Ogień", types: ["Ogień", "Trucizna"] },
  { id: 995, name: "Iron-thorns", type: "Skała", types: ["Skała", "Elektryczny"] },
  { id: 996, name: "Frigibax", type: "Smok", types: ["Smok", "Lód"] },
  { id: 997, name: "Arctibax", type: "Smok", types: ["Smok", "Lód"] },
  { id: 998, name: "Baxcalibur", type: "Smok", types: ["Smok", "Lód"] },
  { id: 999, name: "Gimmighoul", type: "Duch", types: ["Duch"] },
  { id: 1000, name: "Gholdengo", type: "Stal", types: ["Stal", "Duch"] },
  { id: 1001, name: "Wo-chien", type: "Ciemność", types: ["Ciemność", "Trawa"] },
  { id: 1002, name: "Chien-pao", type: "Ciemność", types: ["Ciemność", "Lód"] },
  { id: 1003, name: "Ting-lu", type: "Ciemność", types: ["Ciemność", "Ziemia"] },
  { id: 1004, name: "Chi-yu", type: "Ciemność", types: ["Ciemność", "Ogień"] },
  { id: 1005, name: "Roaring-moon", type: "Smok", types: ["Smok", "Ciemność"] },
  { id: 1006, name: "Iron-valiant", type: "Baśniowy", types: ["Baśniowy", "Walka"] },
  { id: 1007, name: "Koraidon", type: "Walka", types: ["Walka", "Smok"] },
  { id: 1008, name: "Miraidon", type: "Elektryczny", types: ["Elektryczny", "Smok"] },
  { id: 1009, name: "Walking-wake", type: "Woda", types: ["Woda", "Smok"] },
  { id: 1010, name: "Iron-leaves", type: "Trawa", types: ["Trawa", "Psychiczny"] },
  { id: 1011, name: "Dipplin", type: "Trawa", types: ["Trawa", "Smok"] },
  { id: 1012, name: "Poltchageist", type: "Trawa", types: ["Trawa", "Duch"] },
  { id: 1013, name: "Sinistcha", type: "Trawa", types: ["Trawa", "Duch"] },
  { id: 1014, name: "Okidogi", type: "Trucizna", types: ["Trucizna", "Walka"] },
  { id: 1015, name: "Munkidori", type: "Trucizna", types: ["Trucizna", "Psychiczny"] },
  { id: 1016, name: "Fezandipiti", type: "Trucizna", types: ["Trucizna", "Baśniowy"] },
  { id: 1017, name: "Ogerpon", type: "Trawa", types: ["Trawa"] },
  { id: 1018, name: "Archaludon", type: "Stal", types: ["Stal", "Smok"] },
  { id: 1019, name: "Hydrapple", type: "Trawa", types: ["Trawa", "Smok"] },
  { id: 1020, name: "Gouging-fire", type: "Ogień", types: ["Ogień", "Smok"] },
  { id: 1021, name: "Raging-bolt", type: "Elektryczny", types: ["Elektryczny", "Smok"] },
  { id: 1022, name: "Iron-boulder", type: "Skała", types: ["Skała", "Psychiczny"] },
  { id: 1023, name: "Iron-crown", type: "Stal", types: ["Stal", "Psychiczny"] },
  { id: 1024, name: "Terapagos", type: "Normalny", types: ["Normalny"] },
  { id: 1025, name: "Pecharunt", type: "Trucizna", types: ["Trucizna", "Duch"] },
];
