ALTER TABLE public.player_pokemon
  ADD COLUMN IF NOT EXISTS train_hp integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS train_atk integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS train_def integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS train_spa integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS train_spd integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS train_spe integer NOT NULL DEFAULT 0;